plugins {
    id 'com.android.application'
}

android {
    namespace 'mg.appmada.camstyle'
    compileSdk 35

    defaultConfig {
        applicationId 'mg.appmada.camstyle'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.2-premium-budget'
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
